isomerpages/moe-nushigh

- _news-and-events/Primary School Competitions.md
Updated the hyperlink for NMOS from Primary School competition page.
> Updated the hyperlink for NMOS 

- _admissions/Year 1 and 3 Admissions/Admissions FAQs.md
- _admissions/Year 1 and 3 Admissions/Year 1 Admissions.md
- _our-dna/Contact Us/Our Staff.md
- _our-dna/Experiment Explore Excel.md
Updated the following pages: 
- staff list
- Our DNA/EEE page for the formatting using table for module view. (SIG pictures are not standardized yet). 
- FAQ for admission and year 1 admission page.
> Updated staff list, Our DNA/EEE page and FAQ page

- _admissions/Open House/Open House 2023.md
hi ms chong i have updated the open house page
> open house page

- _admissions/Year 1 and 3 Admissions/Admissions for Returning Singapore Citizens, Permanent Residents and International Students.md
- _our-dna/Board of Directors and Governors.md
… Permanent Residents and International Students.md","fileName":"Admissions for Returning Singapore Citizens, Permanent Residents and International Students.md","userId":"1762"}
Hi Ms Chong, Ms Van asked me to update this page
> Admissions update page for ms Van

- _our-dna/Board of Directors and Governors.md
Dear Ms Chong
I have added the vice chairman. Thank you!
> Change to BOD

- _admissions/Year 1 and 3 Admissions/Admissions FAQs.md
- _admissions/Year 1 and 3 Admissions/Year 3 Admissions.md
- _primary-school-competitions/Mathematical Olympiad of SG/Login.md
1.	Our staff page taken out of contact us and placed under our dna
2.	Nmos login link update
> Our Staff page and NMOS link

- _primary-school-competitions/Mathematical Olympiad of SG/News and Updates.md
> NMOS update remove the changes

- _primary-school-competitions/Mathematical Olympiad of SG/News and Updates.md
…dates.md","userId":"2710"}
Hi Ai Lin,
I have udpated the NMOS News and Updates page. Seek your approval
> NMOS results release date

- _admissions/Year 1 and 3 Admissions/Year 1 Admissions.md
- _admissions/Year 1 and 3 Admissions/Year 3 Admissions.md
- _our-dna/Board of Directors and Governors.md
Update on Our DNA/Board of Director/Governor page
- Mr Daniel Teo as treasurer.
- re-arrange the photos (Mr Daniel to first row and push back the rest).
> Our DNA/BOD,BOG Page update

- _admissions/Year 1 and 3 Admissions/Year 3 Admissions.md
Please help to approve. Thank you very much!
> update of year 3 admission 2023

- _admissions/Year 1 and 3 Admissions/Year 3 Admissions.md
update display name of application link
> admission y3 update

- index.md
Updated the homepage infopic for year 1&3 admission and link to the correct page.
> Hompage Infopic update for Year 1 and 3 Admission

- index.md
Change the wording from Admissions to Admission
> Homepage infopic Y1/3 Admission

- _primary-school-competitions/Mathematical Olympiad of SG/News and Updates.md
Hi Ai Lin,
I have updated the following:
Due to unforeseen circumstances, the release of the results for NMOS 2023 will be postponed till further notice. We apologise for any inconvenience caused.
> nmos page news and update

- _admissions/Year 1 and 3 Admissions/Year 1 Admissions.md
Hi Ai Lin
For your approval pls.
Thank you.
> Update newton fun camp date

- _primary-school-competitions/Mathematical Olympiad of SG/News and Updates.md
Hi Ai Lin, 
I have updated the website as the following:
The results for NMOS 2023 are released to the respective primary schools. 
NMOS Committee
24 August 2023
> nmos website updates

- _our-dna/Our Staff.md
Updated staff list based on email from Han Lin (231002/03).
> Our DNA/Our Staff Page Update

- _our-dna/Board of Directors and Governors.md
Updated the BOD BOG Page: 
Professor Er Meng Hwa
**Emeritus** Professor
**School of** Electrical and Electronic Engineering
Nanyang Technological University
> Our DNA/BOD BOG Updated page for Prof Er Meng Hwa

- _admissions/Year 1 and 3 Admissions/Year 1 Admissions.md
1. Correct typo error of SIE
2. Update example dates of PSLE release to illustrate SIE application
3. Update dates for school preference submission
> Update Year 1 Admissions.md

- _admissions/Year 1 and 3 Admissions/Admissions FAQs.md
- _admissions/Year 1 and 3 Admissions/Year 1 Admissions.md
- _students-and-parents/Financial Assistance.md
Dear Ai Lin, for your approval please, thank you!
> Update FAS info and SIE links

- _students-and-parents/Yearbooks.md
Updated yearbook page (under Students and Parents)
- added 2021 link
> Updated Yearbook page

- _primary-school-competitions/Mathematical Olympiad of SG/Contact Us.md
Hi Ai Lin,
I have changed the contact number on the website from 6601 1566 to 6516 5357.
Thank you.
> change of contact number in NMOS website

- _primary-school-competitions/Mathematical Olympiad of SG/Rules & Regulations.md
Updated the marks allocation of the questions.
> NMOS Rules and regulations update

- index.md
Updated hompage banner for Open House 2024: 
- Updated image and wordings
- Updated link to the open house page
> Updated Homepage OH Banner

- _admissions/Year 1 and 3 Admissions/Admissions FAQs.md
- _admissions/Year 1 and 3 Admissions/Admissions for Returning Singapore Citizens, Permanent Residents and International Students.md
- _admissions/Year 1 and 3 Admissions/Year 1 Admissions.md
- _students-and-parents/School Fees.md
School Fees page: 
- updated point number 2, to change Supplementary to Miscellaneous
> Updated School Fees (Student&Parent) Page

- _international-math-challenge/About Singapore.md
- _international-math-challenge/Singapore International Mathematical and Computational Challenge.md
> Updated SIMC page

- pages/Careers.md
Removed the following positions: 
- Non-acad: Exec HR, Senior Exec P&I
- acad: Art, Head MT & Foreign Language
> Updated Career Page

- _data/footer.yml
- pages/contact-us.md
Updated the generic contact us page
> Updated contact us page

- _admissions/Year 1 and 3 Admissions/Admissions FAQs.md
- _admissions/Year 1 and 3 Admissions/Year 1 Admissions.md
- _admissions/Year 1 and 3 Admissions/Year 3 Admissions.md
Update of Year 3 admission application link for 2024 at "Year 3 Admissions" and "Admissions FAQs".
Correct typo of PSLE release date at "Year 1 Admissions"
> Update of Year 3 admission application link for 2024

- _primary-school-competitions/Mathematical Olympiad of SG/News and Updates.md
Hi Ai Lin, I updated the date when NMOS 2024 results will be released. Thank you
> NMOS News and Updates (regarding NMOS 2024 results)

- index.md
Updated homepage banner:
- for Year 1 and Year 3 Admission.
- Updated link to the year 1 and 3 admission page.
> Updated homepage for year 1 and 3 admission link

- _our-dna/Our Staff.md
Updated names and sequences of staff list as of August 2024.
> Staff Page Update

- _news-and-events/Recent Highlights/NUS High Team Emerges Champions at National Science Challenge.md
Removed broken link from recent news/NSC link to CNA article.
https://staging.d1bl70m167uzkq.amplifyapp.com/news-and-events/recent-highlights/nus-high-team-emerges-champions-at-national-science-challenge/
> Removed broken link

- _admissions/Year 1 and 3 Admissions/Admissions FAQs.md
- _admissions/Year 1 and 3 Admissions/Year 1 Admissions.md
For approval before 1 Nov (SIE interest start date)
> Update of SIE application link and interview from 3rd day of PSLE release

- _student-development/Boarding Programme/Billing.md
- _students-and-parents/School Fees.md
Updated school fees and boarding fees pages.
> Updated School Fees and Boarding Fee Giro Dates (2025)

- _students-and-parents/Scholarships and Awards.md
Remove TF scholarship from Students and Parents/ Scholarship and Awards page.
> Remove TF scholarship

- pages/Careers.md
Remove “Assistant Head, Math & Statistics” position under Academic
> Career Page Update

- _admissions/Open House/Open House 2025.md
> update open house date

- _admissions/Open House/Open House 2025.md
Removed the phrase “No pre-registration is required”.
> Updated Open House 2025 Page

- _primary-school-competitions/Mathematical Olympiad of SG/News and Updates.md
Hi Ai Lin, as described above.
> NMOS 2025 results release update
